[character]
success_symbol = '[âœ](bold green) '
error_symbol = '[âœ—](bold red) '

# Git specific configuration
[git_branch]
symbol = 'ğŸ”€ '

[git_commit]
tag_symbol = ' ğŸ· '

# Kubernetes specific configuration
[kubernetes]
disabled = false
symbol = "â˜¸ï¸ "

# Azure specific configuration
[azure]
disabled = false
symbol = 'ó° … '
